name: Selenium Tests

on:
  push:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Dependencies
      run: mvn clean install -DskipTests

    - name: Run Selenium Tests
      run: mvn test
